CREATE TABLE "tradewise-ai_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tradewise-ai_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "tradewise-ai_user_preference" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"userId" varchar(256) NOT NULL,
	"riskTolerance" varchar(50),
	"investmentGoals" text,
	"preferredMarkets" text,
	"notificationsEnabled" boolean DEFAULT true,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "tradewise-ai_user" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"email" varchar(256),
	"phone" varchar(20),
	"fullName" varchar(256),
	"avatarUrl" text,
	"provider" varchar(50),
	"isEmailVerified" boolean DEFAULT false,
	"isPhoneVerified" boolean DEFAULT false,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "tradewise-ai_user_email_unique" UNIQUE("email"),
	CONSTRAINT "tradewise-ai_user_phone_unique" UNIQUE("phone")
);
--> statement-breakpoint
ALTER TABLE "tradewise-ai_user_preference" ADD CONSTRAINT "tradewise-ai_user_preference_userId_tradewise-ai_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."tradewise-ai_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "tradewise-ai_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "tradewise-ai_user_preference" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "email_idx" ON "tradewise-ai_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "phone_idx" ON "tradewise-ai_user" USING btree ("phone");